### ISSUE TITLE
zoom on map using rectangle

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#1]
can we implement a zoom tool on map by drawing a rectangle ?

**Comment by yuvadm** [comment]
Yep we can do that https://www.mapbox.com/mapbox-gl-js/api/#Map.fitBounds

**Comment by yuvadm** [comment]
@mushon discovered we can do this by holding the shift key and choosing the rectangle. we just need to change to a :heavy_plus_sign: cursor on shift

**Comment by yuvadm** [comment]
Use CSS style `cursor: crosshair;`
