### ISSUE TITLE
help page

### ISSUE THREAD

**Issue by amitay7** [daat-hamakom/maps#102]
@josefspr here are some topics to start with, would you want to continue? 
- timeline: dragging timeline up, zoom scrolling, side time dragging 
- search: how to open, comparing timelines
- the side list btn ("on this view")
- photo / video -> lightbox behaviour

**Comment by josefspr** [comment]
what is the basic format of the help - a single document with explanations and screenshots ? or a set of hotspots in different locations in the interface ? will we use tooltips ?

**Comment by mushon** [comment]
- right now we’re thinking of a help page and a short on-boarding (#101) that will explain what it’s about and would recommend the first event to start from (random choice from a pool of recommended events)

**Comment by josefspr** [comment]
reassigned #101
