### ISSUE TITLE
Can we merge Reference, Origin and Quote annotations?

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#103]

**Comment by josefspr** [comment]
yes, we can. 
so here's the summary of annotations (correct me if wrong):
1. reference - between 2 events. directional (determined by origin event) or non-directional (no origin, a reciprocal relation).
2. communication (includes correspondence) - between 2 events. directional or non-directional
3. path - directional, 1-2 events + ordered set of places. origin event is obligatory, if there is a second event it is the end point. The ordered set of places are the points between start and end events.
4. group - of events. not ordered. select/hovering also lights up all paths whose origin event is in the group.

**Comment by mushon** [comment]
Great! @amitay7 please take note.

**Comment by josefspr** [comment]
examples: 
reference, group - project Kol Mekadesh Shevi'i
travel/path (between 2 events) + group - project Early Modern Travellers to the East
I will soon create a project with multiple point paths

**Comment by josefspr** [comment]
small correction for annotations: an arrow/edge annotation can also be 1 event + 1 place (non-event).
this case is applicable for example for the telegrams maps (communication) where there is usually a sending event to a destiny but not a receiving event.

**Comment by yuvadm** [comment]
@josefspr existing `origin` type annotations should be merged into what new type?

**Comment by yuvadm** [comment]
Per https://github.com/daat-hamakom/data/issues/87 - resolved. All existing annotations were merged according to their new types.
