### ISSUE TITLE
zooming to event should show its full annotation

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#111]

**Comment by yuvadm** [comment]
@mushon just to clarify this is an issue for fixing event map context fields, right?

**Comment by josefspr** [comment]
I'm also not completely sure what you mean.

**Comment by mushon** [comment]
Right now when we click a marker that has annotation it zooms to it like any other marker.
We need to make sure we can see the full annotation like travel and reference lines that often require a much wider zoom.
That’s all.

**Comment by josefspr** [comment]
Let's start by overriding map context of annotated events with continent, will cover most cases. If necessary we can consider bounding boxes etc.

**Comment by josefspr** [comment]
override default continent isn't good. for now comment this out, and user will take the annotations in consideration for map context of event.

**Comment by yuvadm** [comment]
Done
