### ISSUE TITLE
default thumbnail and media icon parameter

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#112]
I would recommend the following: 
if the media icon field is empty - use project thumbnail or person thumbnail.

**Comment by mushon** [comment]
I think we already discussed this but the hierarchy should be:

```
if (event icon is set) {
  thumbnail = event icon
} else if (there's metadata marked on the event for person or organization)
  thumbnail = first metadata icon
} else {
  thumbnail = project icon
}
```

cc @yuvadm

**Comment by josefspr** [comment]
event icon you should mean "media icon", no ?

**Comment by mushon** [comment]
I'm not sure what you mean by media icon

**Comment by josefspr** [comment]
In the event form, you can choose which of the media items to use for thumbnail. What I suggest is that if  none is selected, you fallback to person/project. The reason is that in many cases the media is not good as thumbnail (e.g. a text image) and project/person is better.

**Comment by mushon** [comment]
ok, fair enough.
