### ISSUE TITLE
error in youtube clip

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#113]
Event
A Day in Warsaw
Why do I get error in movie ?

**Comment by yuvadm** [comment]
Probably because the URL includes unneccesary metadata `https://www.youtube.com/watch?v=Wr6NgPUl6rI&list=PLD3450A6D953BF223&index=4` it should only have the `v=Wr6NgPUl6rI` part (including the first part obviously), nothing after that

**Comment by josefspr** [comment]
sorry, thought I removed metadata but autocomplete put it back...
