### ISSUE TITLE
Enable the 6 periods for maps

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#117]
the 6 periods:
- Pre-Industrial: Before the French Revolution (1789)
- Industrial: 1789 - 1914 (WWI)
- Modernism: 1914 - 1939 (WWII)
- Dark Times: 1939-1945 (war is over) (if you want it)
- Post-War: 1945-2000 (The Millenium Bug)
- Contemporary: After 2000

**Comment by yuvadm** [comment]
Fixed for pre-industrial events in 7e9d1d876c

Pending further designs

**Comment by mushon** [comment]
awesome!
