### ISSUE TITLE
communication annotation - connect event to place

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#121]
This possibility appears in telegraph map (Rabbi X sending/recieving to/from place Y).  In this case the non-event place will not have it's own marker, right ?

**Comment by mushon** [comment]
right

**Comment by yuvadm** [comment]
Baghdad is one such example event

**Comment by josefspr** [comment]
thanks, looks cool!
<img width="985" alt="screen shot 2016-06-19 at 2 15 27 pm" src="https://cloud.githubusercontent.com/assets/15631729/16176998/89265c08-3628-11e6-834b-32773ddde2e6.png">
