### ISSUE TITLE
Provide Mushon period specific label jsons with type metadata

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#125]

**Comment by yuvadm** [comment]
Here are all the labels for the preindustrial map (pre-1789) https://gist.github.com/yuvadm/94998265bb720d749a6caa1d567099a7

**Comment by yuvadm** [comment]
@mushon ^

**Comment by mushon** [comment]
Thanks, Implemented.
Will we have a more direct way of doing that going forward?

**Comment by yuvadm** [comment]
Of course, this data is generated on the fly on map creation and dynamically inserted as a layer named `[style]-places`. This data is just for you to play with in the studio.

**Comment by mushon** [comment]
ok, we will need to implement the scalerank metadata to avoid cases like this (Great Synagogue at Duke's Court):
<img width="187" alt="screenshot at jun 10 11-49-00" src="https://cloud.githubusercontent.com/assets/27123/15959024/59996a6c-2f01-11e6-93c6-b9cd4628bab7.png">
Please also note the unique characters we will probably need to escape.

**Comment by yuvadm** [comment]
@mushon I can generate a version that includes the scalerank data, just haven't connected that part of the API yet, but it'll probably help you with the testing. Special chars will probably have to be edited in the database itself

**Comment by mushon** [comment]
Ok. Let me know when that can be available.

**Comment by yuvadm** [comment]
@mushon soon, but it probably won't have too much data that differs from the default level unless @josefspr has gotten to updating records

**Comment by yuvadm** [comment]
@mushon https://gist.github.com/yuvadm/335733d573df81bbafcefdf01fb8559b
