### ISSUE TITLE
Put videos in top of event cards (with pics) 

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#129]
In this case, can thumbnail image in map be taken from the video ? (currently I put there a capture of the video, but now this will be redundant).

**Comment by yuvadm** [comment]
@josefspr unfortunately we can't use the thumbnail from the image automatically (it's sligthly complicated to pull the image from youtube and process the thumbnail on client side). eliminating it from the content and putting in on top of the cards will be done as agreed.

**Comment by josefspr** [comment]
that's fine

**Comment by yuvadm** [comment]
Resolved
