### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#132]

**Comment by josefspr** [comment]
Open a pdf document.

**Comment by talbenbasat** [comment]
Hi @mushon,

Would you like to mention where the help and about buton should be placed.

for now they are only opening pdfs.

Thanks,
Tal

**Comment by mushon** [comment]
I will add them in the coming two weeks.

**Comment by mushon** [comment]
Proposed design:
https://invis.io/HC6EQ6L7Q#/215151014_New-Timeline-1_Copy_2

![new-timeline-1 copy 2](https://cloud.githubusercontent.com/assets/27123/22458830/e7627b82-e7a6-11e6-8e02-2d4c46f70f96.png)
