### ISSUE TITLE
Design About page

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#133]

**Comment by josefspr** [comment]
About page should also contain disclaimer and credits.

**Comment by mushon** [comment]
Proposed design:
https://projects.invisionapp.com/d/main#/console/5753463/216751811/preview

![new-timeline-pop-over](https://cloud.githubusercontent.com/assets/27123/22458208/148d653e-e7a4-11e6-9319-70ecb386f342.png)

**Comment by mushon** [comment]
@josefspr please review

**Comment by josefspr** [comment]
I like it, very simple and elegant

**Comment by josefspr** [comment]
Bold font of title does not stand out enough.

**Comment by mushon** [comment]
@talbenbasat & @josefspr please note the original design features a heavier weight and different font combination than the implementation:
![image](https://cloud.githubusercontent.com/assets/27123/25482899/576a36c4-2b5c-11e7-9767-a85c94cc00e5.png)
Current implementation:
![image](https://cloud.githubusercontent.com/assets/27123/25482888/4c511c4e-2b5c-11e7-86e2-2837bce9b5d0.png)

**Comment by mushon** [comment]
@talbenbasat note [the CSS you imported](https://fonts.googleapis.com/css?family=Merriweather) only delivered the regular weight, you should use this import instead: ``<link href="https://fonts.googleapis.com/css?family=Merriweather:400,900" rel="stylesheet">
``

**Comment by talbenbasat** [comment]
@mushon ,

Cooll i'll fix it.

BTW - please try to separate the content to parts.
In the invision the title and the block are in the same block so it appears like they have the same design.
