### ISSUE TITLE
sound player continues to play file of previous event

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#136]
Example: 
play Al Jolson records Hatikva
select Richard Tucker records Hatikva
the player continues to play Al Johnson
only if I close and open event card, the sound file is reset.

**Comment by yuvadm** [comment]
@josefspr this seems to be a bug that occurs deeper in the stack, possibly by react. can we workaround this in the mean time (by closing and opening event cards, as you mentioned)?

**Comment by josefspr** [comment]
Yuval, I would very much prefer that we fix this one, Edwin's lecture is the highlight of the presentation. If it's really deep we'll reconsider.

**Comment by yuvadm** [comment]
@josefspr found a decent workaround :)

**Comment by josefspr** [comment]
bravo!!!
