### ISSUE TITLE
annotations of publishing house do not appear

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#138]
All annotations of publishing houses do not appear (in general or project maps)

**Comment by josefspr** [comment]
there are many other annotations that are not working. e.g.
Telegram by Local Rabbis to the Ottoman government -> Istanbul
Handwritten version of Hatikvah by Naftali Herz Imber -> Naftali Herz Imber purchases his grave with Hatikvah

**Comment by josefspr** [comment]
Annotations of publishing houses still don't work: 
Reestablishment of "Dvir" Publishing House
Establishment of "Stybel" Publishing House
Establishment of "Omanut" Publishing House

**Comment by yuvadm** [comment]
@josefspr Indeed there were two bugs hiding under this issue. both should be fixed now.

**Comment by josefspr** [comment]
great, thanks!!
