### ISSUE TITLE
event thumbnails squashed in cluster list

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#140]
<img width="521" alt="screenshot at jun 29 13-01-28" src="https://cloud.githubusercontent.com/assets/27123/16448347/a4f3b786-3df9-11e6-9a81-a7366e6d2cea.png">

they seem to be getting the wrong image

**Comment by josefspr** [comment]
@talbenbasat the fix causes some thumbnails in the unclusterable card to be missing. Try for example clicking on Berlin.

**Comment by talbenbasat** [comment]
@josefspr 
fixed
please check again
