### ISSUE TITLE
shift of position in hovered modernist map 

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#141]
this seems to be map specific
<img width="465" alt="screen shot 2016-06-29 at 11 20 44 pm" src="https://cloud.githubusercontent.com/assets/15631729/16467629/d444b628-3e50-11e6-830d-aca20a7a72c8.png">

**Comment by yuvadm** [comment]
@mushon this is the issue we discussed last time

**Comment by mushon** [comment]
It's already fixed in master

**Comment by yuvadm** [comment]
master is already deployed :)

**Comment by yuvadm** [comment]
@mushon i still see this bug occurring on master

**Comment by mushon** [comment]
I think I fixed it, please confirm.
