### ISSUE TITLE
default images for missing covers for person and org

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#156]
Mushon can you make them ?

**Comment by mushon** [comment]
Sure @yuvadm what size and format do you want me to use?

**Comment by yuvadm** [comment]
50x50 and 320x214

**Comment by mushon** [comment]
50x50 icons attached (both normal and retina).
Please do not use an image in the card if one does not exist. Thanks!

![ico-institution-def](https://cloud.githubusercontent.com/assets/27123/18781187/735c2ad6-8189-11e6-95d9-659afb8e7855.png)
![ico-institution-def 2x](https://cloud.githubusercontent.com/assets/27123/18781188/735ee816-8189-11e6-96ea-9c5349192159.png)
![ico-person-def](https://cloud.githubusercontent.com/assets/27123/18781189/7364c4c0-8189-11e6-8053-07530889aa32.png)
![ico-person-def 2x](https://cloud.githubusercontent.com/assets/27123/18781190/73669840-8189-11e6-9dc3-712f508de3a1.png)

**Comment by josefspr** [comment]
It looks very nice but don't you feel its quite militant... ?

**Comment by mushon** [comment]
Here's another more abstract option:

Person:
![ico-person-def](https://cloud.githubusercontent.com/assets/27123/18814259/138273ee-831a-11e6-9bdb-3bf620d91e73.png)
![ico-person-def 2x](https://cloud.githubusercontent.com/assets/27123/18814260/1387a0bc-831a-11e6-8432-aca53e8bc982.png)

Org:
![ico-institution-def](https://cloud.githubusercontent.com/assets/27123/18814078/f3cc256a-8317-11e6-8941-15daff888248.png)
![ico-institution-def 2x](https://cloud.githubusercontent.com/assets/27123/18814080/f4087c40-8317-11e6-8ae5-17b989011b88.png)

**Comment by josefspr** [comment]
Are we also talking about the default image appearing in the person/org card ? the format is rectangular landscape, no ? Org is nice, person maybe a less abstract, but its your call

**Comment by mushon** [comment]
These images will only appear in the search autocomplete. In all other cases the card will appear with no image of none is submitted.

**Comment by josefspr** [comment]
Does'nt the card without the image look unbalanced ?

**Comment by mushon** [comment]
I don’t think so, but let’s See it implemented and decide, maybe we will use a background color or something later. But I don’t think it will be needed.

**Comment by talbenbasat** [comment]
HI,

@mushon  can you please resend the final images to place in the cards

thanks,
Tal

**Comment by mushon** [comment]
@talbenbasat please use the images above.

Person:
![ico-person-def](https://cloud.githubusercontent.com/assets/27123/18814259/138273ee-831a-11e6-9bdb-3bf620d91e73.png)
![ico-person-def 2x](https://cloud.githubusercontent.com/assets/27123/18814260/1387a0bc-831a-11e6-8432-aca53e8bc982.png)

Org:
![ico-institution-def](https://cloud.githubusercontent.com/assets/27123/18814078/f3cc256a-8317-11e6-8941-15daff888248.png)
![ico-institution-def 2x](https://cloud.githubusercontent.com/assets/27123/18814080/f4087c40-8317-11e6-8ae5-17b989011b88.png)

**Comment by talbenbasat** [comment]
@mushon ,

Cant extract the assets from invision
https://projects.invisionapp.com/d/main#/console/5753463/169569780/preview

Tal
