### ISSUE TITLE
Add link from event card to meta-card

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#157]

**Comment by yuvadm** [comment]
Links added, pending styles and icons

**Comment by josefspr** [comment]
I see only links to persons, not organizations and projects.
e.g. of organization
https://daat-hamakom-data.herokuapp.com/admin/maps/event/2/change/?_changelist_filters=project__id__exact%3D1

**Comment by yuvadm** [comment]
@josefspr yep, small typo, you should soon see the org links as well

**Comment by josefspr** [comment]
thanks. I think the links should open with meta cards open, right @mushon ?

**Comment by mushon** [comment]
Right.

**Comment by yuvadm** [comment]
@josefspr which meta cards?

**Comment by josefspr** [comment]
By meta cards I mean person, organization and project cards.
In the event card, there should also be a link from the project title to the project link.
