### ISSUE TITLE
Implement default projects list

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#159]
When the user clicks the search box and before she started typing she should see the default screen proposing the list of projects:
![multi cards - researches 2x](https://cloud.githubusercontent.com/assets/27123/18779952/eb0d91ec-8183-11e6-81d2-50bbefa3d562.png)

Only when the user started typing 3 chars should this screen be replaced with the autocomplete list as per ticket #158

**Comment by yuvadm** [comment]
@mushon if we have the projects screen on by default, would that be acceptable? (leaving the search bar behavior as is right now)

**Comment by josefspr** [comment]
@mushon I would like to elaborate the cards view in the search bar. 
first of all the fact that putting the cursor in the search bar or clearing it causes this view to appear is a bit strange and unexpected. Why cannot there be a cards view button on the side of the search bar that opens and closes this view independently of text in search bar ?
second issues is that I lack an overview of the all meta data cards and the number of events each one contains. could the cards view be a nested on - first displaying the meta data types (project, person, organization, tag) and then the cards view according of selected type with number of events in each card ?

**Comment by mushon** [comment]
This is our proposed design:
https://invis.io/HC6EQ6L7Q#/143781086_Multi_Cards_-_Researches

![multi cards - researches](https://cloud.githubusercontent.com/assets/27123/22458353/cbb6cd36-e7a4-11e6-853e-473c2c1350f7.png)

**Comment by talbenbasat** [comment]
@mushon @josefspr 

There is a difference between the timeline and the search by cards height
And I dont understand which one is displayed and when

Can someone please elaborate

**Comment by josefspr** [comment]
Transitions: From what I remember the cards view opens when there is focus on the search bar without typing. After typing 3 chars we get the drop down. we get back to timeline, by clicking on the map.
right, @mushon ? 
Tal has a point about height of the timeline. In the cards view we get a jump that won't look nice.

**Comment by josefspr** [comment]
if there is a single image, arrows of lightbox should not appear

**Comment by talbenbasat** [comment]
Hi @josefspr ,

Unfortunatlly We can't determine in css acording the input length.
but can switch to search when the cursor is inside the search

Tal

**Comment by mushon** [comment]
The cards panel was indeed supposed to be higher than the timeline panel. Since the timeline should be built to expand I suggest we should test the timeline panel in the same height as the search and then make sure it doesn't make the event cards too small.

**Comment by mushon** [comment]
Otherwise, we could transition the heights using CSS animations and by that soften the change. These transitions will be something we will want to do anyway as we will be playing with different panel heights, like in these [4 screens](https://invis.io/FGB6A4XCJ).
