### ISSUE TITLE
Event card should not close when choosing link

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#164]
Permalink should include current event so card will stay open.

**Comment by yuvadm** [comment]
It sounds silly but the way the links are currently implemented this is not really possible. This mainly comes from a limitation in how react router works that it doesn't handle relative links at all right now. I believe the next major version will have some support for this.

**Comment by josefspr** [comment]
I don't understand the problem, for example the permalink to from event card to project card, why can't it include the event
https://daat-hamakom.herokuapp.com/#/project/2/event/10
