### ISSUE TITLE
Add fields to person card

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#165]
Alternative names
Born, Died
Residency

**Comment by yuvadm** [comment]
Done

**Comment by josefspr** [comment]
when one of the list fields, alt name or residency, is empty it puts 0
https://daat-hamakom.herokuapp.com/#/person/88
https://daat-hamakom.herokuapp.com/#/person/13

**Comment by yuvadm** [comment]
@josefspr indeed
