### ISSUE TITLE
Add Search by Event Tags

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#167]
filter by tags field of event.

**Comment by talbenbasat** [comment]
Hi @josefspr,

we added a search by tag and view in the filter
but there is no task for what happens in the case of clicking the tag

Tal

**Comment by josefspr** [comment]
It filters the events that contain this tag. All search functions filter events, thought that was clear.

**Comment by talbenbasat** [comment]
It was but this image by @mushon  confused me

https://github.com/daat-hamakom/maps/issues/158

![image](https://cloud.githubusercontent.com/assets/7951152/21932595/06e494d2-d9aa-11e6-938f-b36c08997dde.png)

**Comment by talbenbasat** [comment]
@josefspr,

The last option shouldnt appear - right?

**Comment by josefspr** [comment]
It should appear, this is the tag result, or maybe did not understand question

**Comment by talbenbasat** [comment]
@josefspr  and when someone clicks on it?
what should happen?

**Comment by talbenbasat** [comment]
you have multiple events linked to it

**Comment by josefspr** [comment]
yes, all the events that have this tag, it will almost always be multiple event, just like 
person, project, org or place

**Comment by talbenbasat** [comment]
@mushon @josefspr what should appear as the metadata of the tag?

**Comment by talbenbasat** [comment]
@mushon @josefspr  what should be under Tag metadata?

**Comment by josefspr** [comment]
a tag does not have metadata

**Comment by josefspr** [comment]
Description: 
Selecting tag filters all events with this tag and creates permalink
https://daat-hamakom-staging.herokuapp.com/#/tag/tag-name
A tag does not have a meta data card
selecting an event on map or timeline from the filtered events opens the event card
and creates permalink https://daat-hamakom-staging.herokuapp.com/#/tag/tag-name/event/event-id
and does not change the filtered events (same as other meta-data filters).

**Comment by josefspr** [comment]
@mushon, we were not sure - in the event card the ‘#’ should’t appear, right ? instead we have to write tags: xxxx yyy_yyy, zzzz …

**Comment by mushon** [comment]
We need to revise previous tags to the format: lowercase_tag
new tags will be transformed on the server.

**Comment by mushon** [comment]
the pound (``#``) Sign will be added in the frontend

**Comment by talbenbasat** [comment]
@josefspr 

This should be done in the server side before save

Talk to me if you wish to execute it or discuss the meanings

**Comment by josefspr** [comment]
You already add it in the event card, so we don't have to do anything special

**Comment by talbenbasat** [comment]
the lower case is the issue
I can add or remove the '#'

**Comment by josefspr** [comment]
why does it have to be done on server

**Comment by josefspr** [comment]
any case we also have to do the _ , I prefer we'll take the db hours from the import project
