### ISSUE TITLE
Undeclusterable label shows count and location

### ISSUE THREAD

**Issue by amitay7** [daat-hamakom/maps#17]
design hierarchy of side bar list of events, and show the cluster under location subtitle such as: "35 events in Tel Aviv"

**Comment by amitay7** [comment]
**location**

**Comment by amitay7** [comment]
![image](https://cloud.githubusercontent.com/assets/16412974/12459351/0483df44-bfb7-11e5-9e84-6f80c5cd7444.png)

**Comment by mushon** [comment]
Redesign this panel to fit current graphic language

**Comment by amitay7** [comment]
![uploads/5d6a1c65-e502-4028-a6b1-a3013d77ef11/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5d6a1c65-e502-4028-a6b1-a3013d77ef11%2Fblob)

**Comment by mushon** [comment]
New design here:
https://invis.io/THA8Y4J27

![new-timeline-1 copy](https://cloud.githubusercontent.com/assets/27123/22461493/2714fa10-e7b2-11e6-81c9-514bfdd39e73.png)
