### ISSUE TITLE
undeclusterable opens side list

### ISSUE THREAD

**Issue by amitay7** [daat-hamakom/maps#18]

**Comment by amitay7** [comment]
suggested designs
![image](https://cloud.githubusercontent.com/assets/16412974/12459322/d1cdfd32-bfb6-11e5-8457-b2cf4caa29d5.png)

![image](https://cloud.githubusercontent.com/assets/16412974/12459333/e0faa756-bfb6-11e5-9781-a897f8da5124.png)

**Comment by mushon** [comment]
Cool.
I think option2 works better than option1, as we don't use that diagonal line anywhere else.
- [ ] Please try to check a darker color for the metadata (research name + year) and for the tags. Right now it looks slightly too pale.
- [ ] Please add the time-frame to the title of the list.
- [ ] we need a hover state for the list
- [ ] does the panel open on hover or on click?

**Comment by yuvadm** [comment]
@mushon heads up that there are some limitations on which elements we can use as markers on the map

https://github.com/mapbox/mapbox-gl-js/issues/358

**Comment by mushon** [comment]
functionality implemented, please review design feedback above ^

**Comment by mushon** [comment]
@amitay7 this should be addressed with #17 and closed when #17 is done

**Comment by amitay7** [comment]
![uploads/45197222-6c17-48e5-a078-ee21cee4318c/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F45197222-6c17-48e5-a078-ee21cee4318c%2Fblob)
