### ISSUE TITLE
Display Copyrights info of images and sounds

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#180]
Image copyrights in lightbox
Sound copyrights in event card (sound control)

**Comment by josefspr** [comment]
@mushon can you complete this one this week ? I need it to prepare Tal's next milestone. It can just be a button on the enlarged image and sound player that opens a model text box.

**Comment by mushon** [comment]
done here:
https://invis.io/6EAF4PJFU

Please note that on the project cards the credit will appear under the scroll

**Comment by josefspr** [comment]
the copyrights is not a single line but is a retailed info window, so I think we need a popup
e.g. https://daat-hamakom-data.herokuapp.com/admin/maps/media/814/change/

**Comment by mushon** [comment]
I think it would be better to use a dropdown for the copyright type and then use an icon to represent it like they do in Vimeo for example:
![image](https://cloud.githubusercontent.com/assets/27123/22862170/46961c78-f132-11e6-8d89-6085facfc5ca.png)

**Comment by mushon** [comment]
We may also want to include both a link to the author and a link to the image like this: 
![image](https://cloud.githubusercontent.com/assets/27123/22862287/805f888e-f134-11e6-8d73-27161e4a0c4f.png)

**Comment by josefspr** [comment]
This can be a solution and we have to decide any case regarding the license type. 
for the the sound files you meant to put it on bottom of event card after description ?

**Comment by mushon** [comment]
Like this:
https://invis.io/HC6EQ6L7Q#/216214397_New-Timeline-3_Copy_7
![image](https://cloud.githubusercontent.com/assets/27123/22862447/61e76932-f137-11e6-94c0-3e08ea04984f.png)

**Comment by josefspr** [comment]
looks fine

**Comment by talbenbasat** [comment]
@mushon, 

we cant change the player entirely.

https://daat-hamakom-staging.herokuapp.com/#/project/4/event/36?_k=dg86pc 

How do you think we should solve the design based on the existing player


Tal

**Comment by mushon** [comment]
why not use [jplayer.org](http://jplayer.org) or some other solution like it that allows styling?

**Comment by mushon** [comment]
in general, there are [tons of solutions](http://www.catswhocode.com/blog/10-awesome-html5-audio-players) that do that

**Comment by talbenbasat** [comment]
@josefspr its your decision
but it wasn't in the original task

**Comment by talbenbasat** [comment]
@mushon 
regarding the lightbox there is a problem when the image is light in the bottom

![daat-lightbox](https://cloud.githubusercontent.com/assets/7951152/24603628/46046eb8-186a-11e7-975f-099ada1cd367.png)

**Comment by talbenbasat** [comment]
as you can see the title contrast isn't good

**Comment by mushon** [comment]
Please note the linear gradient on the image:
![image](https://cloud.githubusercontent.com/assets/27123/24604205/8fd056cc-186c-11e7-9c85-83b1686a4a91.png)

**Comment by talbenbasat** [comment]
@mushon Ok

looks good with it :+1: 

Is there a chance to replace the font  of the copyright to something else.

now it's font-family: "Arial Cyr MT";
Its not a basic or google font and I would prefer it to be.

**Comment by mushon** [comment]
Yes. It's a mistake. The font should be Merriweather Sans like all the rest of the interface.

**Comment by josefspr** [comment]
some lightbox images are too big
https://daat-hamakom-staging.herokuapp.com/#/project/11/event/304?_k=ms9h5x
https://daat-hamakom-staging.herokuapp.com/#/project/11/event/303
some too small
https://daat-hamakom-staging.herokuapp.com/#/project/11/event/302

**Comment by josefspr** [comment]
when media source is empty, there should not be a link and hand on source. 
https://daat-hamakom-staging.herokuapp.com/#/event/302?_k=h1bhin
clicking on source takes me to another copy of map

**Comment by josefspr** [comment]
@mushon don't you think adding gradient to image is distorting - e.g. a poster
https://daat-hamakom-staging.herokuapp.com/#/project/21/event/1040

**Comment by josefspr** [comment]
regarding the player. For this milestone lets work will current player and put title above and copyrights underneath. If we'll have additional hours to spend we'll try replacing.

**Comment by josefspr** [comment]
if there is a single image, arrows of lightbox should not appear

**Comment by talbenbasat** [comment]
Hi @josefspr,

The too big will be solved.
All of the images are at maximum the image size.

Talk to me again about the copy right so i'll create the right conditions with you.

Any case I've uploaded a new version of the lightbox
Please talk to me when you are available

Tal

**Comment by josefspr** [comment]
Regarding caption look at this
<img width="1199" alt="screen shot 2017-04-04 at 4 17 46 pm" src="https://cloud.githubusercontent.com/assets/15631729/24658508/94b924d4-1952-11e7-8faa-2f363630c76c.png">
I think text should be justified to left. @mushon, I also think the caption is too contrasting to copyrights.

**Comment by josefspr** [comment]
@mushon, is there a difference between appearance of word "source" when there is a link to it or only a tooltip ?

**Comment by mushon** [comment]
when there is no link the underline is dashed. otherwise the link is solid

**Comment by mushon** [comment]
The caption overlay in the lightbox doesn't work. I simpler way to do it here:
https://invis.io/HC6EQ6L7Q#/226905063_Lightbox
![lightbox](https://user-images.githubusercontent.com/27123/27992153-7405e87e-6495-11e7-9719-9a0352b7b2e0.png)
