### ISSUE TITLE
Show number of events on timeline

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#183]

**Comment by mushon** [comment]
As mentioned before,  this implementation of a Mapbox React wrapper could be relevant:
https://www.mapbox.com/blog/supercluster/

 I would like @talbenbasat to implement basic clustering and we can then take it from there based on the technical constraints of the clustering plugin.

note [this example](https://www.mapbox.com/mapbox-gl-js/example/cluster/) shows we can configure ``clusterRadius`` meaning we could also choose to only cluster events that appear on the same geolocation (what we called "undeclusterable clusters") which should open the list menu.

**Comment by josefspr** [comment]
@Mushon, this issue was referring to something much more simple - I just want to display the number of events on the map (which changes according to filtering), so its basically just where this number should appear. We should make a separate issue about clustering.

**Comment by mushon** [comment]
Ok, now I understand. Why exactly do we need this?

**Comment by josefspr** [comment]
when we filter, many times there are only one or very few events and its hard to notice if there is anything on the map.

**Comment by mushon** [comment]
And how would this number help?
Rather, filtering should zoom the timeline and the map to the filter extents, that way we can really solve this issue (and that’s in fact the behavior that was planned all along)

**Comment by josefspr** [comment]
you're right lets see it when the zooming works and decide if still neccessary

**Comment by josefspr** [comment]
@talbenbasat lets postphone this task until the zoom and center map/timeline works. It might not be necessary.
