### ISSUE TITLE
Add thumbnail to associated person and organization links in event cards

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#184]
Integration of design:
https://invis.io/HC6EQ6L7Q#/135225566_Selected_Item_-_Sound

**Comment by josefspr** [comment]
updated location of design 
https://projects.invisionapp.com/share/HC6EQ6L7Q#/screens/216948127

**Comment by mushon** [comment]
More precise: https://invis.io/HC6EQ6L7Q#/216214387_New-Timeline-3_Copy_6
