### ISSUE TITLE
Enable zoom and pan on timeline

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#19]
The timeline component should be zoomable and scrollable, an example can be seen at http://bl.ocks.org/mbostock/4015254

Note that using D3 zoom behavior is not possible since we are only using React component behavior for dynamic events. The wheel and mouse events should be captured by React which should then update the relevant D3 action.

Additionally, the axis tick marks should be properly divided into years / months / weeks / days depending on the zoom level.

Relevant code for the component is in https://github.com/daat-hamakom/maps/blob/master/src/components/timeline.js

**Comment by yuvadm** [comment]
@denova Please do the work on a separate branch and open a pull request when ready for code review. No commits to master, please :)

**Comment by yuvadm** [comment]
From Skype conversation:

> The d3.behavior.zoom has a complex structure. Some main points are: 1. onwheel zooming depends on where pointer is sutuated on a chart (i.e. if on a chart from 1950 to 2000 pointer is above 1975 this year will be zoomed by mouse wheel, if is above 1955 - this year will be zoomed), 2. d3.behavior.zoom tracks zooming units (how much wheel was turned around) and selects appropriate zooming level. The way is to rewrite common d3.behavior.zoom (https://github.com/mbostock/d3/blob/master/src/behavior/zoom.js) to React in this case upgrading d3 vendor library will tail difficulties further. This is a long time way as well.
> Another actual issue is mutation of objects by d3. 'React-faux-dom' library handles well static d3 charts but it's not recommended for a lot of DOM manipulations (which zooming is). Thus d3 mutations (like applying time x axis in a d3.behavior.zoom handler) is workaround and this also should be rewritten.

**Comment by yuvadm** [comment]
Work in progress on branch `zoom`

**Comment by yuvadm** [comment]
https://projects.invisionapp.com/share/AD5QTO7WY#/screens/126684728

**Comment by yuvadm** [comment]
`zoom` branched merged and pushed to heroku. Still some rough edges, but zoom and scroll behavior is implemented

+@mushon

**Comment by mushon** [comment]
Cool. This is helpful.
- [ ] I’m assuming the data on the timeline is a mockup though, right? It would be great to see it pulled from the DB and following the design
- [ ] Please implement the click on timeline to zoom and click on left and right margins to zoom out
- [ ] Please implement a limit to zoom-out based on the data + 100 years margin from both sides (meaning if we have data from 1100 to 2016 the maximum extent of the timeline should be 1000-2116)
- [ ] Right now I see some glitches when zooming in as at some point the time spans disappear
- [ ] I would love to see the implementation of the time-spans + circular handles + timeline clusters, I’m assuming this is coming next
- [ ] I would love to see the dynamic behavior of the time spans changing on zoom level

Great job.
That would be all at a first glance.

**Comment by yuvadm** [comment]
Most of these points are now fixed after I've pushed a new implementation of the zoom behavior. I'll open separate tickets for some outstanding issues.
