### ISSUE TITLE
On searchbox focus: Box opens to show horizontal list of researches

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#193]
Integration of design: 
https://invis.io/HC6EQ6L7Q#/143781086_Multi_Cards_-_Researches

**Comment by josefspr** [comment]
@mushon can you make default images for card view of projects, people, orgs, places ?
the card view is working https://daat-hamakom-staging.herokuapp.com

**Comment by josefspr** [comment]
we decided we need place holders for images of projects, people, orgs, places. 
for place image use mapbox generated thumbnail of map

**Comment by josefspr** [comment]
How does hover on card view look ? you wanted to replace the underline to something else

**Comment by mushon** [comment]
Added hover here (#000 title, darker shadow and #D4D4D4 border): 
[https://invis.io/HC6EQ6L7Q#/226905009_Multi_Cards_-_Researches](https://invis.io/HC6EQ6L7Q#/226905009_Multi_Cards_-_Researches)
![multi cards - researches]
![multi cards - researches](https://cloud.githubusercontent.com/assets/27123/25493355/8831e3ca-2b7e-11e7-9a64-c0f2786d444e.png)

the default image should be a background color (#F3F3F3), not an image like here:
[https://invis.io/HC6EQ6L7Q#/220481695_Multi_Cards_-_Places](https://invis.io/HC6EQ6L7Q#/220481695_Multi_Cards_-_Places)
![multi cards - places](https://cloud.githubusercontent.com/assets/27123/25493202/0771668e-2b7e-11e7-9d96-bec18e077a41.png)

**Comment by talbenbasat** [comment]
@mushon 

please share as an invision page

I dont have access to inspect the elements

**Comment by josefspr** [comment]
@mushon  see projects - many project titles get truncated. 
can you suggest how we can add 2-3 more words. If we still need more we might have to add short title field like in wordpress.
