### ISSUE TITLE
Add place thumbnail for search bar results

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#197]

**Comment by mushon** [comment]
![ico-place-def](https://cloud.githubusercontent.com/assets/27123/21961328/bb80c0e4-db0f-11e6-90eb-04864f564e23.png)
![ico-place-def 2x](https://cloud.githubusercontent.com/assets/27123/21961329/bb9dc9fa-db0f-11e6-9b0b-5e7f869192d8.png)
