### ISSUE TITLE
Changing approach for time spans

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#199]
@josefspr 
I looked into the issue of the time spans and I wonder whether we should necessarily show them the way we do now. Right now we centralize the marker in the middle of the span and show the span at all times. This gives a much higher hierarchy to span markers that in some cases can even span centuries and it also marks the center as an arbitrary marker while in many cases the event start is much more substantial than its end. In fact in many span cases like we previously discussed the span is not an actual span but an estimation.

I wonder if it doesn't maybe make more sense to show the span only on hover, especially in the case of estimations. Also we might want to show the marker at the beginning of a span rather than at its middle.

**Comment by josefspr** [comment]
I agree about estimations. there are some century spans that my assistant entered that are not good and we'll remove them. The thing is that the most common use of spans are life periods of people. I would like to see these periods in relation to other things, such as overlapping with other life spans or oeuvres of the same or other people. What I say is the the span is only meaningful in relation to other spans of events.

**Comment by mushon** [comment]
True. Specifically life time spans make no sense in the context of an event. Life is never a single event and should not be presented as such. If we want a separate view for comparison of people's life spans it should be a separate feature.

**Comment by josefspr** [comment]
I am not referring to birth/death timespans but to life periods in places that is very relevant. e.g. - An artist living and working in Berlin and then working in Palestine etc... I you filter by this person your see intervals of life periods, points of oeuvres and annotations that create a mapping of his activity.

**Comment by mushon** [comment]
In that case we can simply choose to activate time spans (before hover) only in filtered mode

**Comment by josefspr** [comment]
so you're suggesting different displays of filtered and non-filtered map/timeline - the timespans and also the layout on y-axis, right ?

**Comment by mushon** [comment]
Yes

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On January 22, 2017 at 10:29:38 AM, josefspr (notifications@github.com) wrote:

so you're suggesting different displays of filtered and non-filtered map/timeline - the timespans and also the layout on y-axis, right ?
