### ISSUE TITLE
media icon parameter in event does not appear as thumbnail

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#214]
e.g.
event: Postcard of synagogue in Frankfurt (event/1104)
Media icon is front side but the thumbnail shown is back side.

**Comment by talbenbasat** [comment]
@josefspr 

Can you please explain more about the bug

**Comment by josefspr** [comment]
@talbenbasat, still not working
https://daat-hamakom-staging.herokuapp.com/#/event/1104

**Comment by talbenbasat** [comment]
![synaguge-in-frankfurt](https://user-images.githubusercontent.com/7951152/27820192-3e43ae58-60a6-11e7-8ac4-ba886ebcbfb3.png)

**Comment by josefspr** [comment]
@talbenbasat how much work is it to make the media icon also determine the event card thumnbnail ?
 because now the thumbnail icon is different than the event card icon.

**Comment by talbenbasat** [comment]
@josefspr 
about 1-2 hours

should i develop it?

**Comment by josefspr** [comment]
yes

**Comment by talbenbasat** [comment]
Done 

took 1.5 extra hours

**Comment by josefspr** [comment]
cool. thanks!
