### ISSUE TITLE
Close current event card on filter change

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#216]
When a filter context is changed, current open card should close only if event does not belong to filter.

**Comment by talbenbasat** [comment]
@josefspr,

please define a coherent logic for closing the event card

**Comment by josefspr** [comment]
Close current event card when selecting Filter only if current event is NOT part of this context.

**Comment by talbenbasat** [comment]
@josefspr 

you mean the event card on the side, right?

**Comment by josefspr** [comment]
yes

**Comment by talbenbasat** [comment]
Hi @josefspr ,

The second option causes problems in the map
So i just did the first option

I dont close the event card when the link is from the event card

**Comment by josefspr** [comment]
@talbenbasat its ok that the card stays open on filters opened from event card. When I open filter from search or cards view sometimes event cards is closed and sometimes open, should be consistent and always close.
