### ISSUE TITLE
card image is should be centered

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#219]
Use background-image to set the image and it will be fixed:

![uploads/4c6722a2-5c4a-4bf9-92bc-efffffeba5cd/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4c6722a2-5c4a-4bf9-92bc-efffffeba5cd%2Fimage.png)

**Comment by talbenbasat** [comment]
@mushon where should it be centred  to?

**Comment by mushon** [comment]
Just use ``background-image`` instead of ``background`` like I mentioned in my comment and it would do the trick

**Comment by talbenbasat** [comment]
completed
