### ISSUE TITLE
Associated filters do not match the design

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#224]
This is how they should look:
![uploads/8afdbc27-cdb8-4af6-876f-420ebb2129ba/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8afdbc27-cdb8-4af6-876f-420ebb2129ba%2Fimage.png)

This is how they currently look:

![uploads/1b44d0b2-9040-4fa4-b615-9f21ee0ff6f6/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1b44d0b2-9040-4fa4-b615-9f21ee0ff6f6%2Fimage.png)

**Comment by talbenbasat** [comment]
@josefspr,

The events JSON doesn't contain the person image.
we can:
1. add the image to the events JSON - increase its size
2. search in the people JSON and get the image from there - consume processing time

Which one would you prefer?

**Comment by josefspr** [comment]
not so happy about 1, regarding 2 - what might it slow down ?

**Comment by talbenbasat** [comment]
@josefspr 
Now we have to search the people in the client-side DB, when we display the event card

**Comment by josefspr** [comment]
@tal the right corners of the rectangle should be rounded

**Comment by talbenbasat** [comment]
@josefspr 
it is - 5px

Changed to 15px to make it more rounded
