### ISSUE TITLE
Contract button should be attached to search bar

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#227]
Designed:
![uploads/75d3dc51-253e-461f-be45-1fb3f32289da/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F75d3dc51-253e-461f-be45-1fb3f32289da%2Fimage.png)

Currently:
![uploads/61ce089c-9148-4b6c-8896-e64e9e5d4958/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F61ce089c-9148-4b6c-8896-e64e9e5d4958%2Fimage.png)

Also please note that in both cases (both open and closed) the button should not have a bottom border and should only reveal the upper half of the circle.

**Comment by josefspr** [comment]
@talbenbasat please replace direction of arrow on button also on selecting search card or text.

**Comment by talbenbasat** [comment]
The direction of the arrow is based on if the metacard is open or not

**Comment by josefspr** [comment]
@mushon I am not sure whether contract button also replaces the close button on the search bar. @talbenbasat says that the contract button is only for opening and closing meta-cards, while the close X on right side is to close the search bar. If this is correct, we should locate contract button a bit more to the left because they don't look good close together.

**Comment by mushon** [comment]
They should never appear together.
There is no reason to see the expand bar when we're in the filter view:
![image](https://user-images.githubusercontent.com/27123/27903552-6414b7b0-6242-11e7-8c1e-ea916adf9063.png)

And there is no need to see the close button when we're on a meta-card:
![image](https://user-images.githubusercontent.com/27123/27903606-9a111b42-6242-11e7-9156-cbe14014b421.png)

The ``X`` on meta cards that is attached to the filter has a different meaning than the ``X`` in the search bar, as it removes the filter. 

I hope this helps clarify.

**Comment by josefspr** [comment]
@talbenbasat the X still appears when onboarding and cards view is open.
X appears on card view (correct) but should also appear on search to be consistent.

**Comment by josefspr** [comment]
@mushon should right side close (X) also appear on text search bar ?

**Comment by mushon** [comment]
Yes, it is the expand button that should not appear there.
