### ISSUE TITLE
timeline labels are mispositioned

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#228]
Should be slightly higher:
![uploads/2dfb402b-17b2-43e6-8a20-488d758f3c9c/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2dfb402b-17b2-43e6-8a20-488d758f3c9c%2Fimage.png)

And they're missing their 3px rounded corners and they should be slightly larger than they currently are:
![uploads/eabdfcfe-6a55-4a08-8e90-4562263a5cc1/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feabdfcfe-6a55-4a08-8e90-4562263a5cc1%2Fimage.png)

**Comment by talbenbasat** [comment]
@mushon 

The line from the event marker to the annotation can't surpass the timeline.
Since the D3 component is drawing the line.

Which one of these options is better?

**Comment by talbenbasat** [comment]
![daat-annotation1](https://user-images.githubusercontent.com/7951152/27686651-64944e32-5cdc-11e7-8a92-0f671c52d660.png)
![daat-annotation2](https://user-images.githubusercontent.com/7951152/27686653-6621476e-5cdc-11e7-9d4a-6c72fdcd2d0e.png)

**Comment by mushon** [comment]
let’s go with the 2nd option (the one without gap)

**Comment by talbenbasat** [comment]
:+1:
