### ISSUE TITLE
Demo 2 different Mapbox map style transitions

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#23]
So we know what we're working towards will indeed look the way we intend it to

**Comment by yuvadm** [comment]
Two relevant demos:

https://www.mapbox.com/mapbox-gl-js/example/setstyle/
https://www.mapbox.com/mapbox-gl-js/example/color-switcher/

We need to aim for the second example, switch only layout props

**Comment by yuvadm** [comment]
As long as we follow the transition-able properties we should be fine: https://www.mapbox.com/mapbox-gl-style-spec/

**Comment by mushon** [comment]
Awaiting two maps with parallel layer structure see issue #28

**Comment by mushon** [comment]
duplicate of #54. Closing
