### ISSUE TITLE
Events displayed on the timeline show line only on hover/select

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#232]
Not on hover/select they show only the circle handle. Only on hover/select the line (time span) is shown.

**Comment by josefspr** [comment]
@talbenbasat I see that the although the line is invisible it reacts to hovering. I would like that only the handle react to hovering.

**Comment by talbenbasat** [comment]
@josefspr You dont want the line anymore?

**Comment by josefspr** [comment]
I want it to be shown on hover/select on the handle. I don't want it to react to hover when its invisible
(so actually doesn't have to react at all).

**Comment by josefspr** [comment]
@talbenbasat line has to appear on hover and select, now it appears only on select. To be more precise - hover on the handle causes the line to appear (now only select does it).

**Comment by josefspr** [comment]
also notice that the line that connect the event to the annotation on hover is also missing.

**Comment by josefspr** [comment]
@mushon I'm trying to choose between 2 possibilities of the hover behavior in timeline. In the production the line although invisible still responds to hover. This makes it harder to miss the marker, but sometimes it covers a bit a nearby event. staging only hovers on the circular handle, but often the hovering misses the handle (you have to move over it very carefully). I think I prefer the reaction of the production version, but please tell me your opinion. thanks

**Comment by mushon** [comment]
I'm definitely with you on the preference of the production version
