### ISSUE TITLE
Change logo of map to Jewish Cultures Mapped

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#235]

**Comment by mushon** [comment]
Done.
https://projects.invisionapp.com/d/main#/console/5753463/226905058/preview

**Comment by josefspr** [comment]
thanks !
@talbenbasat can you update the logo ?

**Comment by talbenbasat** [comment]
Hi @mushon ,

this is the logo I got from the assets.
@josefspr  says It looks different than the old design

![logo svg](https://user-images.githubusercontent.com/7951152/28521647-50d3e63c-707d-11e7-82ac-24e6a3f6ee91.png)

**Comment by josefspr** [comment]
@mushon I liked more the previous font with bold grey subtitle, you sure about new look ?

**Comment by mushon** [comment]
this was a missing font accident. It's already fixed (forgot to update you):
https://projects.invisionapp.com/d/main#/console/5753463/226905058/inspect
