### ISSUE TITLE
cluster + number on map

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#24]
only un

**Comment by yuvadm** [comment]
We can do clusters now that GL JS has shipped 0.13.1 with native clustering support (in addition to `icon-allow-overlap`, see https://github.com/mapbox/mapbox-gl-js/issues/2048) but task is pending further design decisions.

**Comment by yuvadm** [comment]
In the meantime I removed all clustering and allowed icon overlap so we have a better sense of the data.

**Comment by yuvadm** [comment]
@mushon I flipped the switch. Please take a look at the initial cluster impl and see how you like the mechanics (of course marker click behavior etc. is still pending)

**Comment by mushon** [comment]
looking good.
Can you try it with a slightly smaller radius and maybe a 80% opacity?

**Comment by yuvadm** [comment]
@mushon done

**Comment by mushon** [comment]
the map wouldn’t load

![image](https://cloud.githubusercontent.com/assets/27123/13287704/164b0048-db11-11e5-8ba3-ddf7f064439f.png)

**Comment by mushon** [comment]
ok, it works now.

more feedback:
- [x] make cluster smaller
- [x] color the text white
- [x] Does Mapbox support animated clustering / declustering like leaflet does?
- [x] At some point after zooming into a declusterable cluster, the cluster disappears. See Jerusalem:

![uploads/c64e9e78-49ee-474a-bade-5f88d61969b2/7dQbWrwqM3.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc64e9e78-49ee-474a-bade-5f88d61969b2%2F7dQbWrwqM3.gif)

**Comment by yuvadm** [comment]
Mapbox doens't support animated clustering.

And the cluster disappears because I've set a maximum zoom level. I'll make sure it always stays as a cluster.

**Comment by mushon** [comment]
ok, let's keep an eye to see if more clustering features are added and use them if we see fit.

**Comment by yuvadm** [comment]
@mushon Pushed new version with the style fixes

**Comment by mushon** [comment]
awesome, closing.
