### ISSUE TITLE
Safari - lightbox image position and label/copyrights

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#241]
<img width="1219" alt="screen shot 2017-07-16 at 8 22 25 am" src="https://user-images.githubusercontent.com/15631729/28244877-0f4b200a-6a00-11e7-8042-e375a00a2e55.png">

**Comment by mushon** [comment]
rather than fixing that it might be easier to transition to the simpler design I suggested without the text overlaying the image:
https://projects.invisionapp.com/d/main#/console/5753463/226905063/preview

**Comment by josefspr** [comment]
bug does not appear in ver. 9.0
