### ISSUE TITLE
add image thumbnails to markers

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#31]
using sprite. image size: 40_40px (80_80px in retina)

**Comment by yuvadm** [comment]
We have severe sprite limitations at this point. Here's the gist of it:
- Sprites endpoint is implemented per [specification](https://www.mapbox.com/mapbox-gl-style-spec/#sprite) on the backend (https://daat-hamakom-data.herokuapp.com/sprites.json and https://daat-hamakom-data.herokuapp.com/sprites.png)
- Current GL JS API doesn't allow to insert sprite sheet programatically, it must be built into the style in edit-time (i.e. in mapbox studio)
- Current GL JS styling APIs don't allow us to style the images like we want to - specifically I would want `border-radius` to make them round and then add some border. So any advanced styling we want to do has to happen server-side which is pretty ugly.
  - Still no support for complex elements other than sprite images

I think at this point the sensible option is to use pre-styled categorical SVG icons

**Comment by mushon** [comment]
understood.
I would suggest we indeed work with categorical SVG and then communicate with an HTML layer above them to overlay images and html content.

**Comment by yuvadm** [comment]
The HTML overlay is not a trivial task to implement. I'll sniff around the uber react repo since they did similar stuff, but unless there something i can easily adapt, I'm not sure this fits our scope.

**Comment by mushon** [comment]
make editable square thumbnails to fit the marker size.
