### ISSUE TITLE
why doesn't the site work on my safari, only on chrome

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#32]
any idea ?

**Comment by yuvadm** [comment]
what exactly isn't working?

**Comment by josefspr** [comment]
the map doesn't show up

**Comment by yuvadm** [comment]
just the map? what about the timeline? can you post some screenshots?

**Comment by yuvadm** [comment]
Safari seems to have WebGL disabled by default, a very weird decision.

Enable it: http://onvert.com/guides/enable-webgl-safari/

**Comment by josefspr** [comment]
in my version the enable option does not appear. chrome works fine, the issue is wether there are many browsers that do not support WebGL, we have to check out this issue thouroughly

**Comment by yuvadm** [comment]
WebGL is fully supported on all modern browsers, and then some (mobile included) http://caniuse.com/#feat=webgl

**Comment by yuvadm** [comment]
This issue is probably best dealt with in #22 where we notify the user of the base browser requirements: webgl, JS, screen resolution
