### ISSUE TITLE
Design event cards

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#38]

**Comment by mushon** [comment]
current status (not closed yet):

![uploads/4a765861-f5d4-40bb-ad3f-cc91a74a3bb4/selected item.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4a765861-f5d4-40bb-ad3f-cc91a74a3bb4%2Fselected+item.png)

**Comment by mushon** [comment]
- [x] mock up different image aspect ratios
- [x] add lightbox prompt icon on the image
- [x] mock up full screen image
- [x] mock up embeds further down the card scroll
- [x] account for time spans in metadata

**Comment by mushon** [comment]
![uploads/102b8918-c11d-4947-8df7-9e47db770aeb/selected item + sound.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F102b8918-c11d-4947-8df7-9e47db770aeb%2Fselected+item+%2B+sound.png)

![uploads/5c33512c-3951-454a-bcf2-ecc8f81f2ed4/selected item + video.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5c33512c-3951-454a-bcf2-ecc8f81f2ed4%2Fselected+item+%2B+video.png)

**Comment by amitay7** [comment]
![uploads/a6bc0f62-d8ff-4dda-b3cd-8d7fa43cd3d4/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa6bc0f62-d8ff-4dda-b3cd-8d7fa43cd3d4%2Fblob)

**Comment by mushon** [comment]
@yuvadm, I sent you the access to invisionapp where you'll find the assets folder. You can download them from: https://projects.invisionapp.com/d/main#/projects/5753463/assets
