### ISSUE TITLE
Implement initial timeline

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#5]

**Comment by yuvadm** [comment]
Reference D3 implementation: https://github.com/jiahuang/d3-timeline/blob/master/src/d3-timeline.js

**Comment by yuvadm** [comment]
Another good one: https://github.com/emeeks/d3.layout.timeline/blob/master/src/timeline.js

**Comment by yuvadm** [comment]
![styletiles 2](https://cloud.githubusercontent.com/assets/315080/12080616/b8a9a7f8-b268-11e5-9f0a-46eb7e9e4993.png)
![styletiles 3](https://cloud.githubusercontent.com/assets/315080/12080617/b8acabba-b268-11e5-9e4f-2a20d396ab54.png)

**Comment by josefspr** [comment]
thnx, can we see it actually working on a site ? 

Date: Sun, 3 Jan 2016 12:24:33 -0800

**Comment by yuvadm** [comment]
No, this isn't implemented yet

**Comment by yuvadm** [comment]
@mushon Can we get some color specs for the style tiles?

**Comment by mushon** [comment]
Since colors will be dynamic anyway I suggest you implement with (50 >) shades of gray and we will later play with the colors via CSS (SCSS? SASS?)

**Comment by yuvadm** [comment]
Of course, just thought I can get the original ones so I can get a better feel of how I'm making progress.

**Comment by yuvadm** [comment]
Proper D3/react separation:

https://github.com/freddyrangel/playing-with-react-and-d3

http://qumulo.com/blog/front-end-engineering-at-qumulo-react-d3-js/

**Comment by yuvadm** [comment]
All the scaffolding is in place. Closing this issue and follow further progress on #19 and #20
