### ISSUE TITLE
implement cards design

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#53]

**Comment by mushon** [comment]
design:
https://invis.io/5T61MJWXW

**Comment by mushon** [comment]
- [ ] implement oEmbed
- [ ] implement audio embed
- [ ] implement image gallery
- [x] implement design in css
- [x] use [OpenSans](http://www.opensans.com/) as default font

**Comment by yuvadm** [comment]
We have all these. Specifics in new tickets
