### ISSUE TITLE
demo 2 map style transition w diff

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#54]

**Comment by mushon** [comment]
Here we go:
[diff-2-maps.zip](https://github.com/daat-hamakom/maps/files/144900/diff-2-maps.zip)

**Comment by mushon** [comment]
Actually let's try with this one instead (more changes in the red map):
[diff-2-maps.zip](https://github.com/daat-hamakom/maps/files/146325/diff-2-maps.zip)

**Comment by mushon** [comment]
@yuvadm just a friendly reminder that this is a priority for us. ;)

**Comment by yuvadm** [comment]
@mushon i'm on this

**Comment by yuvadm** [comment]
@mushon please take a look at the current map. 10 Seconds after loading it will change the style to the one you gave me. Seems to perform rather well!

**Comment by mushon** [comment]
Thanks @yuvadm, but please note the transition wasn't complete. On the left you can see what the map should have looked like and on the right what it currently does after transition:

![uploads/3224a229-3cdc-4d48-97c4-0acb287db5a9/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3224a229-3cdc-4d48-97c4-0acb287db5a9%2Fblob)

You will see that:
1. the textures that weren't used before weren't loaded
2. the fonts that weren't used before weren't loaded
3. the text halo was supposed to be removed and didn't
4. the borders that were supposed to disappear, didn't

in fact it seems like only colors transitioned, the other properties either disappeared (textures) or were ignored (borders, halos, fonts)

It might just be that assets need to be loaded in advance (like in the case of the markers) to later be transitioned in. That could explain the fonts and the textures but not the halo and border. What could explain the latter two is if elements have to be present on the map and cannot be hidden, but rather faded to 0% opacity or something like that.

So what I suggest we try is to go the other direction. I updated [the JSON file in the Gist here](https://gist.github.com/mushon/e5e3011fc1996355a1a8) you will see all the revisions tracked there and the latest version has references to all assets (SVGs and fonts). It also has all the layers that I wanted hidden set to opacity: 0 or line-width: 0. What I would like you to do is to start from this map (the red one) and transition to the blue one. I think that would do the trick. Please also make the transition slower so I can better inspect it. If there's a way for me to toggle the transition back-and-forth rather than wait for it to happen, that would even be better.

Would you please look into it?
Thanks.

**Comment by yuvadm** [comment]
I thought we agreed that only paint properties are part of the diff. In any case I added the layout properties as well since they are also easy to switch (`setPaintProperty()` and `setLayoutProperty()` APIs). This is already deployed.

Next will be to do the switch the other way around and have some nice buttons for it. Will get to that later today.

**Comment by mushon** [comment]
we need all the diff to change, some will change via transition, other would just flip through, but we need them all to change.
If you’re adding buttons, it would also be great to have an input field for the transition duration ;)

Thanks

**Comment by yuvadm** [comment]
If you expect anything else to change other than paint/layout props than expect that those might not work since I don't have APIs for them

**Comment by mushon** [comment]
I’m not clear on the terminology. what types of properties can or cannot change?

**Comment by yuvadm** [comment]
Paint and layout properties on each layer, see https://www.mapbox.com/mapbox-gl-style-spec/#layers

**Comment by mushon** [comment]
I think paint and layout properties cover quite a lot and I don’t think we will need anything beyond that

Mushon Zer-Aviv
Mushon.com http://mushon.com/ | Shual.com http://shual.com/ | @mushon http://twitter.com/mushon

**Comment by yuvadm** [comment]
@mushon Your diff has two extra layers "building copy 1" and "building copy 2". (See https://gist.github.com/mushon/e5e3011fc1996355a1a8/revisions) That might be affecting why the diff doesn't complete properly. Take a look at the currently deployed version (still on the 10 sec timer, sorry).

**Comment by mushon** [comment]
Possibly simpler solution - use the built in [compare API](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-compare/) with a twist:

![uploads/004ae054-f01b-4163-b24b-0751e7b5941d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F004ae054-f01b-4163-b24b-0751e7b5941d%2Fblob)

The idea is that on hover the target map will appear in a cropped circle (essentially border radius on the canvas element + the right transform) and on click the circle will grow to fill the frame.
The screenshot above shows that change should be possible in CSS + JS on the `#after canvas` element + some adjustments for scale in the GL API. (there are possibly other ways of doing that with [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) but I'm not sure about their browser support).

Anyway, this might be an equally good (if not better) way of doing transitions that would save us the headache of diffs, GL transitions and layer standardizations. What say you @yuvadm ?

**Comment by mushon** [comment]
also relevant: http://stackoverflow.com/questions/15007903/html5-canvas-with-rounded-corner

**Comment by yuvadm** [comment]
@mushon I'm not sure what this gives us. I'll need to manage state on `N` different maps and this is no less of a hack than what we're doing now.

**Comment by mushon** [comment]
Ok. I will call to discuss this tomorrow.

**Comment by yuvadm** [comment]
aye

**Comment by mushon** [comment]
Please call me when you’re available for a short conversation.

**Comment by yuvadm** [comment]
Follow on #63
