### ISSUE TITLE
Un/declusterable cluster click behavior

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#59]
- Undeclusterable should open event list in sidepane
- Declusterable should zoom to cluster extent

**Comment by yuvadm** [comment]
This isn't completely resolved, but navigating to a single event is possible now:
- zoom in on the relevant location
- once the cluster markers changes into a ring marker, click on it
- if it's a single event you'll see it
- if there are many events on the same location, click on the event will lead you to the event page
- @josefspr

**Comment by josefspr** [comment]
that's great, thanks. one remark - if there are several events on same location it's a cluster until
zooming then becomes a marker, this is a bit confusing.Would it be possible not to display as cluster ? I suppose this is more complicated to solve, you can try fixing when you're back.

**Comment by yuvadm** [comment]
If it's easier, I can disable clustering entirely until we have the final behavior working. This might help during the content creation period.

**Comment by josefspr** [comment]
no, you can leave it like this.

**Comment by josefspr** [comment]
no, in second thought lets disable clustering...

**Comment by yuvadm** [comment]
Done

**Comment by yuvadm** [comment]
Bringing back clusters in #75
