### ISSUE TITLE
map skin: Pre industrial times

### ISSUE THREAD

**Issue by amitay7** [daat-hamakom/maps#6]

**Comment by mushon** [comment]
Current version available here:
https://api.mapbox.com/styles/v1/mushon/cijzh5hn000zzbmkv7sw2g5os.html?title=true&access_token=pk.eyJ1IjoibXVzaG9uIiwiYSI6IjY1bHhhTkEifQ.DhW2zcurHHBtmnc2FsMBqg#4/38.01065548424398/18.680128565568253/0
