### ISSUE TITLE
screenshot of map opening on part of screen

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#60]
<img width="1280" alt="map bug" src="https://cloud.githubusercontent.com/assets/15631729/13486467/1561e07a-e11a-11e5-94c7-b7713f813ab5.png">

**Comment by mushon** [comment]
I can confirm that I've been getting this bug myself more often than not

**Comment by yuvadm** [comment]
@mushon when this happens for you, do you see any anomaly in the map element styling? if you inspect the map div, what are it's extents?

**Comment by mushon** [comment]
Something seems to assign 300px height to the canvas element. Look:
![image](https://cloud.githubusercontent.com/assets/27123/13495460/8ff26ac4-e153-11e5-900e-d33b253a7e31.png)

Another pointer for you could be the fact that resizing the browser fixes things. Maybe something miscalculates the size of the screen and when another resize event is fired, all is aligned again?

**Comment by yuvadm** [comment]
Weird. Those 300px aren't coming from my code as far as I can tell.
