### ISSUE TITLE
Minimal recommended size for images

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#65]
In some cases its easier to get copyrights for a lower res, so tell me what minimal size still
looks got in the lightbox.

**Comment by mushon** [comment]
This really depends on the original image and how detailed it is.
I would say that images that are lower than 800px wide or 600px high are not worth showing in the lightbox.
Hopefully we will get images that are of much higher resolution than that and we will be able to show them in sizes that are more around 1600*1200px
