### ISSUE TITLE
some movie don't work although links are ok

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#69]
example event Collaborative balloon mapping in mt. scopus, the youtube link is fine.
<img width="945" alt="screen shot 2016-03-21 at 11 18 02 am" src="https://cloud.githubusercontent.com/assets/15631729/13914405/df0a72f8-ef56-11e5-9384-e612c207da77.png">

**Comment by yuvadm** [comment]
This seems to be a problem with the video itself on youtube. The video works fine on https://www.youtube.com/watch?v=C2k5PB2Ez_c but clearly is broken when using the embed URL https://www.youtube.com/embed?v=C2k5PB2Ez_c

**Comment by yuvadm** [comment]
Ignore. I found a way to workaround the bad link. https://www.youtube.com/embed/C2k5PB2Ez_c works fine
