### ISSUE TITLE
map skin: Industrial

### ISSUE THREAD

**Issue by amitay7** [daat-hamakom/maps#7]

**Comment by mushon** [comment]
How about this?
https://api.mapbox.com/styles/v1/mushon/ciqs382tn0013cbnhsvd3rl8r.html?title=true&access_token=pk.eyJ1IjoibXVzaG9uIiwiYSI6IjY1bHhhTkEifQ.DhW2zcurHHBtmnc2FsMBqg#4/38.01065548424398/18.680128565568253/0

![image](https://cloud.githubusercontent.com/assets/27123/16919499/9b02807c-4d12-11e6-9c9e-ea13e33150c5.png)

**Comment by josefspr** [comment]
I'm a bit color blind, but isn't it similar to pre-industrial and in general all 3 maps pre, indust., modern
are in quite a similar palette in relation to the last two ?

**Comment by mushon** [comment]
It is true that the first three maps are more monochromatic than the post-war one. It is quite deliberate as the history of map changed that way and the post-war map was deliberately designed to look more optimistic than the other ones. The "Dark Times" map is the definitely deliberate outlier.
With that being said, I do agree that the modern and the 19th century maps are a bit too close. I will work on both of them to differentiate their scheme a bit.

**Comment by mushon** [comment]
I reworked the Modernism map. I think it is much more Modernist now, it is also much different than the other ones. [Here's a link](https://api.mapbox.com/styles/v1/mushon/ciqtl1jtd000kc6nhue3u38q4.html?title=true&access_token=pk.eyJ1IjoibXVzaG9uIiwiYSI6IjY1bHhhTkEifQ.DhW2zcurHHBtmnc2FsMBqg#3.3998692809553828/40.629525497341234/18.380131644852042/0) and here's a before & after comparison:

![image](https://cloud.githubusercontent.com/assets/27123/16955643/171d41bc-4dde-11e6-9136-50f46f315076.png)

What do you think?

**Comment by josefspr** [comment]
yes, I like it much more (:-
