### ISSUE TITLE
Query string based project filtering

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#70]
@josefspr I've implemented an initial version of filtering by project via URL query string. To launch it, type the following URL in a clean window (this won't work if your current tab is already open on Daat Hamakom).

For example: https://daat-hamakom.herokuapp.com/#/project/2 will only show the Ha'Measef events. The ID `2` is taken from the admin interface (so in this example Ha'Measef is edited in URL https://daat-hamakom-data.herokuapp.com/admin/maps/project/2/change/)

**Comment by yuvadm** [comment]
Future work on the filters will make this process much more user-friendly, this is just to get you going per request.

**Comment by josefspr** [comment]
when I use the query string filter in chrome I always get bug #60 opening of part of map

**Comment by josefspr** [comment]
<img width="1280" alt="screen shot 2016-03-23 at 9 46 14 am" src="https://cloud.githubusercontent.com/assets/15631729/13978788/6b9c085e-f0dc-11e5-888e-412827822c2a.png">

**Comment by josefspr** [comment]
where can I see the ids of the projects ?

**Comment by yuvadm** [comment]
@josefspr IDs can be taken from the admin, see my first comment.

As for #60, that's very weird. It happens only with filtered URLs, and never happens otherwise?

**Comment by josefspr** [comment]
It happens also without filter, but after I refresh it once, it is ok, so actually #60 was not solved yet...
