### ISSUE TITLE
design / choose theme for html5 audio-tag

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#72]

**Comment by amitay7** [comment]
base it on:
https://projects.invisionapp.com/d/main#/console/5753463/135225566/preview

**Comment by amitay7** [comment]
![image](https://cloud.githubusercontent.com/assets/16412974/14777085/69ea47ee-0ad3-11e6-8d90-aa9df1770f4b.png)

**Comment by amitay7** [comment]
![sound-pause 1x](https://cloud.githubusercontent.com/assets/16412974/14777755/d7641792-0ad7-11e6-8e06-91c9340515ae.png)
![sound-pause 2x](https://cloud.githubusercontent.com/assets/16412974/14777758/d785b3ca-0ad7-11e6-8528-8bc8847105c2.png)
![sound-play](https://cloud.githubusercontent.com/assets/16412974/14777756/d7647188-0ad7-11e6-8087-0592abc6d432.png)
![sound-play 2x](https://cloud.githubusercontent.com/assets/16412974/14777754/d7637300-0ad7-11e6-9d78-5b2cf0fba02c.png)

**Comment by amitay7** [comment]
![sound-pause](https://cloud.githubusercontent.com/assets/16412974/14779166/83a703f0-0adf-11e6-944c-75a60c555503.png)
![sound-pause 2x](https://cloud.githubusercontent.com/assets/16412974/14779168/83a9c694-0adf-11e6-9962-4b7d939d0e69.png)
![sound-play](https://cloud.githubusercontent.com/assets/16412974/14779167/83a9768a-0adf-11e6-9356-758fee74cb15.png)
![sound-play 2x](https://cloud.githubusercontent.com/assets/16412974/14779169/83ac6430-0adf-11e6-83e3-ce51957a8ac8.png)

**Comment by amitay7** [comment]
![image](https://cloud.githubusercontent.com/assets/16412974/14779195/a4f1a038-0adf-11e6-88dd-e570175415fb.png)

**Comment by yuvadm** [comment]
Example: Sound Recording of Gilat Center, Beer Sheva

As designed right now requires a special JS widget, let's stick to CSS props only.

**Comment by mushon** [comment]
WE need to go with something that is simpler to implement over the default HTML5 player

**Comment by mushon** [comment]
It seems that we cannot customize each browser's audio player implementation. The only way to go is to build the player and hook it to the HTML5 api with JS.

**Comment by mushon** [comment]
we'll keep it to the default HTML5 audio player
