### ISSUE TITLE
Design icon for document download

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#73]
in the card description

**Comment by josefspr** [comment]
@yuvadm and @amitay7 can we implement this one soon ? I need it for some of the researchers projects. thanks

**Comment by mushon** [comment]
Here you go:

![uploads/4ba76d8e-6424-4859-a7f4-b03bd5497e9f/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4ba76d8e-6424-4859-a7f4-b03bd5497e9f%2Fblob)

![uploads/b9a0bb5a-451f-4731-a0b3-d2efaa938a7c/doc_icon.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb9a0bb5a-451f-4731-a0b3-d2efaa938a7c%2Fdoc_icon.png)

![uploads/e9421b0e-959c-49d9-a62e-031b6c598889/doc_icon@2x.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe9421b0e-959c-49d9-a62e-031b6c598889%2Fdoc_icon%402x.png)

**Comment by josefspr** [comment]
event with document:
Bassola Visits in Pula
