### ISSUE TITLE
Add map zoom controls

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#77]
Zoom in, zoom out, rotate back to North

**Comment by amitay7** [comment]
![image](https://cloud.githubusercontent.com/assets/16412974/14066032/4c8cfec2-f448-11e5-8fa2-5ef5a54ac7c0.png)
[map_btns.zip](https://github.com/daat-hamakom/maps/files/190965/map_btns.zip)

**Comment by josefspr** [comment]
@yuvadm can the zoom in and out be in a transition, not a discrete step ?

**Comment by yuvadm** [comment]
@josefspr current zoom API doesn't do transitions. (neither does this happen on scroll, for example)

**Comment by mushon** [comment]
Maybe this required passing the transition values through the Zoom API?

**Comment by yuvadm** [comment]
There's no such option as far as I can tell. I can maybe test doing an incremental zoom. So instaed of `map.setZoom(zoom+1)` I do `zoom+0.1` 10 times.

**Comment by mushon** [comment]
That’s what I meant :)

**Comment by yuvadm** [comment]
a'ight, will test this.

**Comment by yuvadm** [comment]
@mushon no visible effect even when adding steps, there's a rendering buffer somewhere beyond my control.

**Comment by yuvadm** [comment]
also, see https://github.com/mapbox/mapbox-gl-js/issues/1730

**Comment by mushon** [comment]
Try using this
https://www.mapbox.com/mapbox-gl-js/example/flyto/

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by yuvadm** [comment]
@mushon sweet, I didn't know flyTo accepts a zoom transition. Nice catch!

**Comment by josefspr** [comment]
coolissimo!
