### ISSUE TITLE
Add lightbox controls

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#81]

**Comment by yuvadm** [comment]
Added in `lightbox` branch merge

**Comment by josefspr** [comment]
thanks very much. there is issue of different sizes of images, that cause the caption and controls to jump up and down does not look nice, and if the image is very large it overlays on them. I would suggest that we limit the max size of light box, and keep the caption and controls in same position, what do you say ?
Example cases:
Ran Morin - The Botanical Garden
Helmar Lerski as cinematographer of expressionist films
Catholic German Church Lied, 17th Century (Source)

**Comment by yuvadm** [comment]
@josefspr sorry I thought I fixed that, thanks for the example cases.

**Comment by josefspr** [comment]
Another thing: the lightbox should open in the image selected in card, not in first image.

**Comment by yuvadm** [comment]
@josefspr that should be the current behavior, is it not?

**Comment by josefspr** [comment]
When enlarging an image from the card, the lightbox should open on the current image, not the 1st one
