### ISSUE TITLE
Missing event list icon

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#83]
Missing assets for this icon:

![1459331368](https://cloud.githubusercontent.com/assets/315080/14138421/de9ec532-f675-11e5-95af-3c49cfb7aa6a.png)

**Comment by amitay7** [comment]
added more icons and updated the first ones
[daat Icons.zip](https://github.com/daat-hamakom/maps/files/197279/daat.Icons.zip)

**Comment by amitay7** [comment]
also - here is the main design spec, you can also in it in the Invision folder
[specs.pdf](https://github.com/daat-hamakom/maps/files/197315/specs.pdf)

**Comment by yuvadm** [comment]
:+1:
