### ISSUE TITLE
Add marker assets for non-default styles

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#84]
Once we have them, use them in the style transitions.

**Comment by mushon** [comment]
I need a data source which I can point MBstudio at and use it to style the markers differently based on their metadata. Any pointers for how might I go about doing that?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by yuvadm** [comment]
I don't think you need to do that at all, leave that to me. I just need the new assets.

For example, now we have the blue `default-marker`s. If you can just add an asset called `preindustrial-marker` I'll (hopefully) be able to change the markers on the fly when toggling styles. I hope we're keeping them the same shape, just different colors?
