### ISSUE TITLE
Display event subtitle

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#85]
do we have design for this ?

**Comment by amitay7** [comment]
![image](https://cloud.githubusercontent.com/assets/16412974/14779344/665a95b8-0ae0-11e6-88e7-7f0c5a272ab5.png)

**Comment by yuvadm** [comment]
@mushon is this finalized?

**Comment by mushon** [comment]
yes please :)

**Comment by mushon** [comment]
@josefspr did we decide to drop this? Or is this still something we want to support?

**Comment by josefspr** [comment]
we dropped subtitle in event card, should only appear in project card.

**Comment by mushon** [comment]
just wanted to make sure, closing.
