### ISSUE TITLE
smearing of image in event card

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#87]
Proportions issue, many places, example:
Kol Mekadesh Shevi'i melody Attributed to the Baal Shem Tov (Tel-Aviv)
Perhaps crop the right proportions.

**Comment by yuvadm** [comment]
Yep this is a bug in the last thumbnails update. Fixing.

**Comment by josefspr** [comment]
still smeared
Helmar Lerski as cinematographer of expressionist films
3rd image of metropolis

**Comment by yuvadm** [comment]
@josefspr I don't see any smears there. can you clear browser cache and provide a screenshot?

**Comment by josefspr** [comment]
<img width="418" alt="screen shot 2016-04-13 at 4 54 08 pm" src="https://cloud.githubusercontent.com/assets/15631729/14495514/779e4654-0198-11e6-88c4-118dedc96bcc.png">

**Comment by yuvadm** [comment]
you're seeing a stale image, did you clear browser cache?

**Comment by josefspr** [comment]
sorry you're right...
