### ISSUE TITLE
missing thumbnails

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#89]
events:
Hans G. Casparius in Germany
Hans G. Casparius in Palestine (Dead Sea)
Hans G. Casparius in Palestine (Tel-Aviv) - 1 image not appearing
Can you tell me what is wrong with files (currently you can deal with blank spaces in filename, no ?)

**Comment by yuvadm** [comment]
I've already recommended not to work with whitespaces in filenames. Theoretically we support them, but they're always a cause for trouble, as is evident in this case. I'll take a look.

**Comment by yuvadm** [comment]
should be fixed now
