### ISSUE TITLE
map skin: Dark times

### ISSUE THREAD

**Issue by amitay7** [daat-hamakom/maps#9]
tagged styling ("dark times")

**Comment by amitay7** [comment]
tagged styling ("dark times")

**Comment by amitay7** [comment]
https://api.mapbox.com/styles/v1/amitay7/ciieev3bv003d9xkj4cfvd9rd.html?title=true&access_token=pk.eyJ1IjoiYW1pdGF5NyIsImEiOiJjaWllYjh1cGwwMDFidnNrdXM1MDI0N2Y5In0.lX2c7kIOBc85UFbyVmcMyA#2.4909622394421564/33.327408176772096/-0.026507189003552867/0
![image](https://cloud.githubusercontent.com/assets/16412974/12399797/bcf0d8c8-be24-11e5-8450-d98f12b9d99e.png)

**Comment by mushon** [comment]
can’t see it. :/
would you publish + share a link?
- post a screenshot?

Thanks!

**Comment by amitay7** [comment]
Did both when I updated yesterday. Still can't see it?

**Comment by mushon** [comment]
Try sending the share link again

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by amitay7** [comment]
https://api.mapbox.com/styles/v1/amitay7/ciieev3bv003d9xkj4cfvd9rd.html?title=true&access_token=pk.eyJ1IjoiYW1pdGF5NyIsImEiOiJjaWllYjh1cGwwMDFidnNrdXM1MDI0N2Y5In0.lX2c7kIOBc85UFbyVmcMyA#6.822799466302727/9.555310209588527/7.095509350498446/0

**Comment by mushon** [comment]
let's wait with this one for the map base to be ready (#28)

**Comment by mushon** [comment]
Done
