### ISSUE TITLE
lightbox size overflow

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#92]
I did open or mention this one before, but cannot find it. Can you fix it soon ? it shouldn't be difficult.
example event
Publication of Naftali Herz Imber's Barkai
screenshot:
<img width="1278" alt="screen shot 2016-04-17 at 9 02 53 am" src="https://cloud.githubusercontent.com/assets/15631729/14585381/50811476-047b-11e6-8ec4-169642c77e69.png">
original image:
![herz imber words](https://cloud.githubusercontent.com/assets/15631729/14585385/8ed92a2e-047b-11e6-8efe-da20da7201a7.jpg)
like we said, image height should be go beneath controls

**Comment by yuvadm** [comment]
@mushon can you take a look at the lightbox styling and recommend a fix for this?

**Comment by mushon** [comment]
use 90vh and 90vw
See: http://snook.ca/archives/html_and_css/vm-vh-units

**Comment by josefspr** [comment]
Its almost there but part of text still gets covered.
Hans G. Casparius in Heringsdorf
Catholic German Church Lied, 17th Century (Münster)
