### ISSUE TITLE
magnifying glass control on event card thumbnails

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#93]
couldn't find that one also. do we have design for this ?

**Comment by mushon** [comment]
@josefspr  I'm sorry but I'm not sure I understand what you mean by that

**Comment by josefspr** [comment]
is it this ?
<img width="92" alt="screen shot 2016-04-17 at 6 39 06 pm" src="https://cloud.githubusercontent.com/assets/15631729/14588193/cc39597a-04cb-11e6-943b-aa7fd5a93241.png">
its a bit unnoticable, no ?

**Comment by amitay7** [comment]
thicker and with some shadow:
![image](https://cloud.githubusercontent.com/assets/16412974/14779804/7939931c-0ae2-11e6-9968-fad85b1c4a04.png)

also have now rollover versions:
![i-expand rollover](https://cloud.githubusercontent.com/assets/16412974/14779784/5faeae5a-0ae2-11e6-9608-d76ebbf30671.png)
![i-expand rollover 2x](https://cloud.githubusercontent.com/assets/16412974/14779781/5fa6de14-0ae2-11e6-9ecd-e66caf07af72.png)
![i-expand](https://cloud.githubusercontent.com/assets/16412974/14779782/5fa7b3a2-0ae2-11e6-93fb-847034f0355b.png)
![i-expand 2x](https://cloud.githubusercontent.com/assets/16412974/14779783/5fa8a7e4-0ae2-11e6-8481-04e281f813de.png)

**Comment by josefspr** [comment]
There are a few problems: 
On bright background not seen (e.g. Catholic German Church Lied, 17th Century (Source))
It doesn't behave right when you are not on it magnifying works, when you are on it it doesn't
Why not just change the cursor when anywhere on thumbnail ?

**Comment by mushon** [comment]
@amitay7 please address @josefspr's point above

**Comment by mushon** [comment]
sorry, Amitay please make the drop-shadow more emphasized

**Comment by amitay7** [comment]
more shadow:
![i-expand](https://cloud.githubusercontent.com/assets/16412974/14882745/d8e194e2-0d42-11e6-949d-81f7c0aafb44.png)
![i-expand 2x](https://cloud.githubusercontent.com/assets/16412974/14882746/d8e5b374-0d42-11e6-92a8-9f996cd5621f.png)

**Comment by josefspr** [comment]
Didn't we decide that that we use a magnify cursor instead of a located magnifying button ?

**Comment by mushon** [comment]
yes, let’s do that.
