### ISSUE TITLE
Annotations implementation

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/maps#97]

**Comment by yuvadm** [comment]
Things are looking good for creating annotations via a GeoJSON source. Starting from line annotations.

+@mushon @josefspr

**Comment by yuvadm** [comment]
Annotations react to interaction only (click, hover), pending exact spec

**Comment by josefspr** [comment]
please display annotations also on hover.

**Comment by yuvadm** [comment]
@mushon I need the line-pattern assets to be available to me on the style. Are they ready?

**Comment by mushon** [comment]
how do you want me to input them. Do you want me to simply send them to you?

**Comment by yuvadm** [comment]
No i just need them to be available on the style per https://www.mapbox.com/mapbox-gl-style-spec/#paint-line-pattern

**Comment by mushon** [comment]
These 4 files have been added to the map style. Please add them in 10px width.
For reference:
[annotations.zip](https://github.com/daat-hamakom/maps/files/276208/annotations.zip)

**Comment by yuvadm** [comment]
@mushon I'll also need non-default markers that I can use to highlight group annotations

**Comment by yuvadm** [comment]
@mushon cool, starting to look good on my side, I can see and use and assets. However, I need a definition of which ones to use in which context. A reminder that we currently have 4 types of annotations:
- reference
- group
- path
- communication

Which asset should I use in which case? And note that groups require a separate marker as mentioned above

**Comment by mushon** [comment]
- ann_origin.svg = reference
- grouped-marker.svg = group (change all group markers to this)
- ann_travel.svg = path
- ann_communication.svg = 1 way communication
- ann_correspondance.svg = 2 way communication

**Comment by yuvadm** [comment]
@mushon muchos gracias!

**Comment by josefspr** [comment]
Mazal tov on the annotations !!
Liked the travel and communication (only directional was implemented, right?)
Reference is a bit strange for me, feels like some kind of echo or transmission and is also too thick.
In general all of them could be thinner or lighter.

**Comment by yuvadm** [comment]
@josefspr yes, directionality is still not fully implemented. and I agree they all need to be thinner.

**Comment by yuvadm** [comment]
@josefspr @mushon the current group markers don't stand out enough, please take a look at the current deployed version.

**Comment by mushon** [comment]
why do the default markers appear under the group markers?
![image](https://cloud.githubusercontent.com/assets/27123/15539201/cccb24c8-2289-11e6-964f-70355e6c2a38.png)

**Comment by yuvadm** [comment]
@mushon because just changing the marker icons is more complicated than it seems, so I'm adding them for now

**Comment by mushon** [comment]
Ok, this obviously affects the design as well, here's another attempt:
![image](https://cloud.githubusercontent.com/assets/27123/15543524/e539a99e-229d-11e6-81fc-9d13dbdca850.png)

Either way, I really don't understand what to make of the use of groups here really…

**Comment by josefspr** [comment]
Can we try to make them blink ? or some other animation, because the large size is disrupting other markers.

**Comment by josefspr** [comment]
The new reference pattern is very nice !

**Comment by josefspr** [comment]
here are a few examples of groups:
https://daat-hamakom.herokuapp.com/#/project/4 : oberland local tradition (hungary/Israel)
https://daat-hamakom.herokuapp.com/#/project/7: Bassola's travels (there will be other travelers)
https://daat-hamakom.herokuapp.com/#/project/8: works of 2 film creators Lerski and Casparius

**Comment by yuvadm** [comment]
@mushon this isn't a restriction for you, just a temporary measure for me.

**Comment by yuvadm** [comment]
@mushon do we have a new line width that looks better than 10px?

**Comment by mushon** [comment]
Yes. 7px

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon
