### ISSUE TITLE
font sizes in event card

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#98]
Are the sizes of fonts finalized? I have the impression that fonts, especially description can be smaller so you don't have to scroll so much, but perhaps this is also an accessability limitation...

**Comment by mushon** [comment]
We can try 15px instead of 16px. I will keep it as an issue for me to look into once I get into the CSS.

**Comment by mushon** [comment]
actually, @yuvadm would you change the default font size to 15px? I don't want to mess up your code right now and it's a simple change that would help us understand better what we're dealing with.

**Comment by yuvadm** [comment]
@mushon feel free to commit and push to `master` branch. it's always good for editing.
